# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        sudo apt-get -qq install r-base-core
        sudo apt-get -qq install r-cran-rcurl r-cran-bitops r-cran-rjson r-cran-statmod
        mkdir ~/MyRlibs
        sudo R -e 'install.packages("h2o",lib="~/MyRlibs")'
        sudo R < code/H2O_Code_Without_DL.R --no-save

