# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    # The type of runner that the job will run on
    container: ubuntu:18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository -y ppa:marutter/rrutter3.5
        add-apt-repository -y ppa:marutter/c2d4u3.5
        apt-get update
        apt-get install -y r-base 
        apt-get install -y r-cran-tidyverse r-cran-bitops r-cran-catools r-cran-vinecopula r-cran-ks r-cran-data.table r-cran-rapportools
        apt-get install -y r-cran-rcurl r-cran-bitops r-cran-rjson r-cran-statmod libssl-dev
        apt-get install -y openjdk-8-jdk
        mkdir ~/MyRlibs
        
        R -e 'install.packages("h2o",lib="~/MyRlibs")'
        # R < code/H2O_Code_Without_DL.R --no-save
        # R < code/H2O_Code_Only_DL.R --no-save
        R < code/nestedCopulasModelExample.R --no-save
        
