# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        sudo add-apt-repository ppa:marutter/rrutter3.5
        sudo add-apt-repository ppa:marutter/c2d4u3.5
        sudo apt-get update
        sudo apt-get install r-base r-api-3.5 r-cran-rcolorbrewer r-cran-scales r-cran-cellranger r-cran-ggplot2 r-cran-readxl
        sudo apt-get install r-cran-tidyverse r-cran-bitops r-cran-catools r-cran-vinecopula r-cran-ks r-cran-data.table r-cran-rapportools
        sudo apt-get install r-cran-rcurl r-cran-bitops r-cran-rjson r-cran-statmod libssl-dev
        mkdir ~/MyRlibs
        R -e 'install.packages("h2o",lib="~/MyRlibs")'
        R < code/H2O_Code_Without_DL.R --no-save
        R < code/H2O_Code_Only_DL.R --no-save
        R < code/nestedCopulasModelExample.R --no-save
        
